### ISSUE TITLE
输入输出的具体是什么

### ISSUE THREAD

**Issue by Lie-huo** [songlin/d3roma#1]
看论文里写的输入输出都是视差，但是在推理代码里输入输出都是深度，而且输入输出深度图的值域差别还很大。可以明确一下输入输出的含义具体是什么吗，是深度还是视差，他们是怎么转换的，以及在真机部署时如何使用这个预测的深度吗

**Comment by songlin** [comment]
你好，

模型的输入和输出都是视差:

https://github.com/songlin/d3roma/blob/867d8b2968f80455b441f045c46e384a6f25cfb5/inference.py#L171-L178

推理代码为了点云可视化，利用相机的内参进行了视差到深度的转换，具体代码见

https://github.com/songlin/d3roma/blob/867d8b2968f80455b441f045c46e384a6f25cfb5/inference.py#L202-L203


关于真机部署，主要是相机内参的处理。





接入真机相机的步骤：

1. 用已知真机相机的内参，创建一个相机对象。我们测试了`RealSense D415`和`RealSense D435`, 如果您使用这两款相机可以很轻松接入模型，可以参考这里的代码（我们使用的D415相机的内参）：

https://github.com/songlin/d3roma/blob/867d8b2968f80455b441f045c46e384a6f25cfb5/utils/camera.py#L385-L410

这样配置是因为D415的深度图与RGB图不是一个参考系，需要通过变换才能投出深度和RGB对齐的点云。

2. 获取相机拍的左、右视图，以及相机输出的深度图 raw depth。如果是`realsense`之类的主动结构光相机的话，除了左、右视图还有一个RGB图。（RGB图只是为了可视化， 模型实际上只需要左右视图、以及raw dpeth）

3. 推理之前：需要将相机输出的raw depth 通过内参转换成视差，然后和左、右图，RGB图一起输入模型。模型输出的是修复后的视差`pred_disps`。 最后再通过内参变换成depth。

以上具体步骤可以参考`inference.py` 的 `D3RoMa.infer()`

**Comment by Lie-huo** [comment]
> 你好，
> 
> 模型的输入和输出都是视差:
> 
> https://github.com/songlin/d3roma/blob/867d8b2968f80455b441f045c46e384a6f25cfb5/inference.py#L171-L178
> 
> 推理代码为了点云可视化，利用相机的内参进行了视差到深度的转换，具体代码见
> 
> https://github.com/songlin/d3roma/blob/867d8b2968f80455b441f045c46e384a6f25cfb5/inference.py#L202-L203
> 
> 关于真机部署，主要是相机内参的处理。
> 
> 接入真机相机的步骤：
> 
> 1. 用已知真机相机的内参，创建一个相机对象。我们测试了`RealSense D415`和`RealSense D435`, 如果您使用这两款相机可以很轻松接入模型，可以参考这里的代码（我们使用的D415相机的内参）：
> 
> https://github.com/songlin/d3roma/blob/867d8b2968f80455b441f045c46e384a6f25cfb5/utils/camera.py#L385-L410
> 
> 这样配置是因为D415的深度图与RGB图不是一个参考系，需要通过变换才能投出深度和RGB对齐的点云。
> 
> 2. 获取相机拍的左、右视图，以及相机输出的深度图 raw depth。如果是`realsense`之类的主动结构光相机的话，除了左、右视图还有一个RGB图。（RGB图只是为了可视化， 模型实际上只需要左右视图、以及raw dpeth）
> 3. 推理之前：需要将相机输出的raw depth 通过内参转换成视差，然后和左、右图，RGB图一起输入模型。模型输出的是修复后的视差`pred_disps`。 最后再通过内参变换成depth。
> 
> 以上具体步骤可以参考`inference.py` 的 `D3RoMa.infer()`



步骤2中相机输出的深度图raw depth是RealSence相机的IR Projector采集到的深度图还是指左右视图处理后得到的？(因为相机会自动返回一个用左右视图处理得到的深度图)，我用的第二种方式的深度图作为模型的输入，但是对于透明的矿泉水瓶子，模型的结果并没有比输入的深度图好？
除此之外，第一时间图像中的夹爪深度直接给整没了，不知道什么原因，很苦恼

**Comment by Lie-huo** [comment]
不好意思，IR Projector只是红外点阵发射器，不是相机，不输出深度图～
另外看到我们的左右红外图像的红外散斑不太一样，示例图中的是规则的点阵，我采集到是没有规则红外点阵，不知道这个在图像中的差异会不会影响模型的效果

**Comment by songlin** [comment]
raw depth是指相机自己输出的深度图（一般是相机用自己的算法利用左右IR计算视差）。我们实验过程中发现IR斑对模型效果影响不是很大。夹爪这种太细小的物体可能是处理的不够好，我们的模型主要是对瓶子以及类似大小的物体进行训练的。

**Comment by Lie-huo** [comment]
我采集到的图像是1280*720的，用的也是D435相机，推理时把参数也设置成了d435，但是对于空矿泉水瓶子，深度估计结果并没有比输入深度图好，只是做了平滑的感觉，请问大概是什么原因啊

**Comment by songlin** [comment]
@Lie-huo hi 你方便把原文件发出来吗？

**Comment by Lie-huo** [comment]
图片不太方便发，可以加微信私发给你吗？我的微信号 18710568869

**Comment by Lie-huo** [comment]
> @Lie-huo hi 你方便把原文件发出来吗？

或者我把图片发你邮箱呢？

**Comment by songlin** [comment]
slwei@stu.pku.edu.cn

**Comment by Lie-huo** [comment]
> [slwei@stu.pku.edu.cn](mailto:slwei@stu.pku.edu.cn)

songlin博士，昨天上午把数据发您邮箱了，您看着是哪里有问题吗，是我们模型使用的问题还是我们采集的数据问题？

**Comment by Lie-huo** [comment]
hi 上周发的数据有分析结果了吗

**Comment by songlin** [comment]
您好，我用您提供的数据实现发现是可以处理这个情况的，代码发您邮箱了。
![pred](https://github.com/user-attachments/assets/b824d23c-3dbc-45a6-87f7-e330675ed590)
