### ISSUE TITLE
是否打算训练量化版本模型？

### ISSUE THREAD

**Issue by moyesok** [songlin/d3roma#2]
想问一下是否有打算训练fp16版本的模型， 以及turbo版本？ 另外现在开源的模型训练耗时是多久呢？ 谢谢

**Comment by songlin** [comment]
你好，

目前开源模型是用一台8卡a100节点训练的，训练时间大概是8-10个小时。我们没有训练过fp16，但代码应该是支持的。另外，我不太了解turbo版本， 请问有相关资料吗？

**Comment by moyesok** [comment]
谢谢答复， fp16确实可用。 turbo版本指的是蒸馏版本，见 https://stability.ai/research/adversarial-diffusion-distillation
