### ISSUE TITLE
输入的左右图像是对齐（rectify)后的吗?

### ISSUE THREAD

**Issue by YOODS-Xu** [songlin/d3roma#3]
您好！非常感谢您的工作。
请问左右图像是对齐(rectify)后的吗?

**Comment by songlin** [comment]
您好！是的，感谢关注。

**Comment by YOODS-Xu** [comment]
多谢您在百忙之中，迅速赐教。请问这个算法对输入的视差图的质量依赖大吗？如果输入的视差图很差，也能生成有意义的视差图吗？
