### ISSUE TITLE
对输入的视差图的质量依赖大吗？

### ISSUE THREAD

**Issue by YOODS-Xu** [songlin/d3roma#4]
您好！多谢您对上一个问题的迅速解答。请问这个算法对输入的视差图的质量依赖大吗？如果输入的视差图生成的点群包含很多无效点，这样的视差图也能生成有意义的结果视差图吗？

**Comment by songlin** [comment]
D3RoMa算法很依赖视差图的质量。理想的视差图应该少有飞点且总体精度可靠（洞除外），目前这一版算法的主要优势体现在1）对无纹理、透明、反射等物体进行补全，2）对原始视差图的噪声抑制（表现为算法输出的视差比原始视差更平滑），当原始视差图出现非常大面积的无效点的时候，是有可能导致模型效果下降的。

**Comment by YOODS-Xu** [comment]
多谢您百忙之中的详细讲解。大面积的无效点时由于透明和反射物体的大小造成的。

**Comment by YOODS-Xu** [comment]
![Screenshot from 2024-12-04 17-52-15](https://github.com/user-attachments/assets/411631e1-cbe4-40e6-9ceb-b8481dc4ed35)
![Screenshot from 2024-12-04 17-55-31](https://github.com/user-attachments/assets/6aae32cb-ca7a-4c86-abd0-7e615ff4b866)

**Comment by YOODS-Xu** [comment]
这样的点云图对应的视差图会导致模型效果下降吗

**Comment by songlin** [comment]
这个场景中的塑料袋子我认为可能会有难度，因为我的训练数据集都是刚体，都是一些常见的透明和半透明的物体。您有结果吗？可以分享一下吗

**Comment by YOODS-Xu** [comment]
多谢您百忙之中的答复。现在的问题是把raw.ply和pred.ply放到一起时，地面的部分有几毫米的距离。pred.ply稍高些。感觉应该是我定义相机时，参数没设对。
我们的相机是双目的LED结构光相机。没有IR镜头，是2个RGB镜头，不过加了偏光镜，实际上是灰度图。
我定义成RGBD相机，class RGBDCamera(DepthCamera),2个相机参数分别是左右相机的参数。

 def default_ycam():
        """ copy from toolkit v2 """
        cam =  RGBDCamera("640x480", {
            "intrinsic": [974.7257204169617, 974.7257204169617, 329.55003311685, 245.16814592852066], # fx, fy, cx, cy
            "distortion": [-0.023986007442631654, -0.4691885232541908, -0.00009384688302807587, 0.0016899873628167142, 2.0113087576344024], # k1, k2, p1, p2, k3
        },{
            "intrinsic": [976.7586531357327, 976.7586531357327, 342.113054001492, 234.27998566396403],
            "distortion": [-0.04947927461377676, -0.05969887726585017, 0.0014935713163512743, -0.0018309132275525922, -0.24444317495933404]
        }, [
            [0.9916524843511808, 0.000478754482553281, 0.12893843908732797, -80.92916507796178],
            [0.001223614505959081, 0.999913135537834, 0.013123419769174279, -0.16176020374985242],
            [-0.12893352181520504, 0.013171642761728048, 0.9915657591805425, 4.57901130447566],
            [0, 0, 0, 1],
        ]
        )
        cam.device = "ycam"
        cam._baseline = 24.54705 / 974.7257204169617 # hack: so fxb is same as realsense
        return cam

输入给程序的是以下数据。
1)	左右视图是校正后的左右视图
2)	原始深度图
3)	RGB图是校正后的左视图

不好意思，请您受累我的设定哪里有问题。
再次感谢。

**Comment by songlin** [comment]
我看不出问题，但我感觉几毫米误差可能是正常。模型并没有强制输出与raw完全一致。

**Comment by YOODS-Xu** [comment]
多谢您的指教
